language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/18.0.1
  - sudo android-sdk-linux/tools/android -s update sdk --filter android-7,platform-tool --no-ui
  - sudo android-sdk-linux/tools/android -s update project --path ./FridgeMagnet
  - sudo android-sdk-linux/tools/android -s update test-project --path ./FridgeMagnetTest -m ../FridgeMagnet
before_script:
  - pwd
  - ls -la
  - ls -la  android-sdk-linux
  - ls -la  android-sdk-linux/platform-tools
  - ls -laR android-sdk-linux/build-tools/
  - ls -laR android-sdk-linux/build-tools/18.0.1/
  - ls -la  android-sdk-linux/build-tools/18.0.1/aapt
  # Just see if aapt can be run now it's been installed
  - file ./android-sdk-linux/build-tools/18.0.1/aapt
  - chmod 777 ./buildstuff.sh
script: "./buildstuff.sh"
